/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "0810272.h"


void
pdvsa_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  pedir_tiempos_1_arg;
	int  *result_2;
	ticket  pedir_gasolina_1_arg;
	ticket  *result_3;
	reto  validar_respuesta_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PDVSA_PROG, PDVSA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = pedir_tiempos_1(&pedir_tiempos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = pedir_gasolina_1(&pedir_gasolina_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = validar_respuesta_1(&validar_respuesta_1_arg, clnt);
	if (result_3 == (ticket *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	pdvsa_prog_1 (host);
exit (0);
}
