/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "0810272.h"

int *
pedir_tiempos_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
pedir_gasolina_1_svc(ticket *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

ticket *
validar_respuesta_1_svc(reto *argp, struct svc_req *rqstp)
{
	static ticket  result;

	/*
	 * insert server code here
	 */

	return &result;
}
